# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-11-19 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bdd_evenement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(default=' ', max_length=400)),
                ('texte', models.TextField(default=' ')),
                ('img', models.FileField(upload_to='image_venement/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evenement',
                'ordering': ['id'],
            },
        ),
    ]
