# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-11-19 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bdd_evenement',
        ),
    ]
