# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-11-19 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0003_bdd_evenement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bdd_mail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mail', models.CharField(default=' ', max_length=400)),
            ],
            options={
                'verbose_name': 'Mail',
                'ordering': ['id'],
            },
        ),
    ]
